import PlaygroundSupport
import SwiftUI

//: # The basics
//: ## Basic views
/*:
 Let's quickly re-introduce the basic views so that we can start using them!
*/

struct TestView: View {
    var body: some View {
        // VStack
        VStack {
            Text("VStack")
            Text("lays")
            Text("things")
            Text("out")
            Text("vertically")
        }
        
        // HStack
//        HStack {
//            Text("HStack")
//            Text("does")
//            Text("the same")
//            Text("horizontally")
//        }
        
        // ZStack
//        ZStack {
//            Circle()
//                .foregroundColor(.yellow)
//                .frame(width: 200, height: 200)
//            Text("ZStack Uses the Z axis!")
//        }
        
        // Image
//        Image(systemName: "flame")
//            .resizable()
//            .aspectRatio(contentMode: .fit)
//            .frame(width: 100)
        
        // Shapes
//        VStack(spacing: 16) {
//            Rectangle()
//                .foregroundColor(.blue)
//                .frame(width: 100, height: 50)
//
//            RoundedRectangle(cornerRadius: 10)
//                .foregroundColor(.yellow)
//                .frame(width: 100, height: 50)
//
//            Circle()
//                .foregroundColor(.red)
//                .frame(width: 100, height: 50)
//
//            Capsule()
//                .foregroundColor(.green)
//                .frame(width: 100, height: 50)
//
//            Path { path in
//                path.addEllipse(in: CGRect(x: 0, y: 0, width: 100, height: 50))
//            }
//            .foregroundColor(.purple)
//            .frame(width: 100, height: 50)
//        }
    }
}

//: ## Every view modifier is a View
/*:
 In SwiftUI, every time you call a view modifier, the target view is wrapped in another view (or views) generated by the view modifier.
*/
/*struct TestView: View {
    var body: some View {
        VStack {
            Text("And")
            Text("now")
            Text("for")
            Text("something")
            Text("completely")
            Text("different")
        }
        .redColored()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .greenColored()
        .padding()
        .blueColored()
    }
}*/

let testView = TestView()
PlaygroundPage.current.setLiveView(testView)
